# Generated by Django 5.2.6 on 2026-02-17 18:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_auth_provider_user_google_id_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(help_text="Subdomain identifier (e.g., 'acme' for acme.nittiva.com)", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase alphanumeric with hyphens, 1-63 characters', regex='^[a-z0-9]([a-z0-9\\-]{0,61}[a-z0-9])?$')])),
                ('name', models.CharField(help_text='Organization/company name', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active')),
                ('is_trial', models.BooleanField(default=False, help_text='Whether tenant is on trial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_owner_i_58be35_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_owner_i_597fe2_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_name_3fb8fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_project_fe19a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_due_dat_0359a9_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this client belongs to', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this project belongs to', null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this membership belongs to', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this task belongs to', null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this assignment belongs to', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Tenant this user belongs to', null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant_id', 'owner'], name='clients_tenant__cb1f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant_id', 'name'], name='clients_tenant__176571_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant_id', 'owner'], name='projects_tenant__652359_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant_id', 'status'], name='projects_tenant__63edab_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant_id', 'name'], name='projects_tenant__d3c87a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['tenant_id', 'project'], name='project_mem_tenant__2e1a71_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['tenant_id', 'user'], name='project_mem_tenant__f8326b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'project'], name='tasks_tenant__44587b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'status'], name='tasks_tenant__aa382f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'due_date'], name='tasks_tenant__15004a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['tenant_id', 'task'], name='task_assign_tenant__ad9feb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['tenant_id', 'user'], name='task_assign_tenant__edb6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'email'], name='users_tenant__afadfd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'is_active'], name='users_tenant__2f74ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'email'), name='unique_tenant_email'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
    ]
