# Generated by Django 5.2.6 on 2026-02-21 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tenant_remove_client_clients_owner_i_58be35_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this invitation belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Unique invitation token', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email address of invited user', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Role to assign when accepted', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from inviter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, help_text='User who received the invitation (if already registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.project')),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'email'], name='invitations_tenant__898574_idx'), models.Index(fields=['tenant_id', 'status'], name='invitations_tenant__ec457f_idx'), models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['project', 'email'], name='invitations_project_65b4f3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'email', 'status'), name='unique_pending_invitation')],
            },
        ),
    ]
