# Generated by Django 5.2.6 on 2026-02-21 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique company identifier (e.g., ACME123). Users need this to register/login.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Subdomain identifier (optional, for backward compatibility)', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase alphanumeric with hyphens, 1-63 characters', regex='^[a-z0-9]([a-z0-9\\-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company_id'], name='tenants_company_9ec61b_idx'),
        ),
    ]
