# Generated by Django 5.2.6 on 2026-02-21 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tenant_company_id_alter_tenant_subdomain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this attachment belongs to', null=True)),
                ('content_type', models.CharField(max_length=20)),
                ('object_id', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('file_url', models.URLField(help_text='S3 URL or storage path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this comment belongs to', null=True)),
                ('content_type', models.CharField(max_length=20)),
                ('object_id', models.UUIDField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this goal belongs to', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('achieved', 'Achieved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalLinkedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this link belongs to', null=True)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('initiative', 'Initiative')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goal_linked_entities',
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this time log belongs to', null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_manual', models.BooleanField(default=False, help_text='True if manually entered, False if from timer')),
                ('description', models.TextField(blank=True, help_text='Description of work done', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtasks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.PositiveIntegerField(blank=True, help_text='Story points for estimation', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='work_item_type',
            field=models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('request', 'Request')], default='task', help_text='Type of work item (Epic, Story, Task, Bug, Request)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'work_item_type'], name='tasks_tenant__eabe90_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'parent'], name='tasks_tenant__ba53f3_idx'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_goals', to='api.goal'),
        ),
        migrations.AddField(
            model_name='goallinkedentity',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_entities', to='api.goal'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='api.task'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant_id', 'content_type', 'object_id'], name='attachments_tenant__260a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant_id', 'uploaded_by'], name='attachments_tenant__1afe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant_id', 'content_type', 'object_id'], name='comments_tenant__c27d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant_id', 'author'], name='comments_tenant__361964_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant_id', 'status'], name='goals_tenant__ea0de3_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant_id', 'owner'], name='goals_tenant__a66df5_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant_id', 'parent_goal'], name='goals_tenant__493942_idx'),
        ),
        migrations.AddIndex(
            model_name='goallinkedentity',
            index=models.Index(fields=['tenant_id', 'goal'], name='goal_linked_tenant__10b04b_idx'),
        ),
        migrations.AddIndex(
            model_name='goallinkedentity',
            index=models.Index(fields=['tenant_id', 'entity_type', 'entity_id'], name='goal_linked_tenant__46a01c_idx'),
        ),
        migrations.AddConstraint(
            model_name='goallinkedentity',
            constraint=models.UniqueConstraint(fields=('goal', 'entity_type', 'entity_id'), name='unique_goal_entity'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['tenant_id', 'task'], name='time_logs_tenant__3f7728_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['tenant_id', 'user'], name='time_logs_tenant__ba5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['tenant_id', 'started_at'], name='time_logs_tenant__c878d5_idx'),
        ),
    ]
