# Generated by Django 5.2.6 on 2026-02-28 17:27

import api.models.custom_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attachment_comment_goal_goallinkedentity_timelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this field belongs to', null=True)),
                ('id', models.CharField(default=api.models.custom_field.CustomField._generate_id, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Field name/label', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('rating', 'Rating'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('width', models.PositiveIntegerField(default=150, help_text='Column width in pixels')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown fields')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_fields',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'order'], name='custom_fiel_tenant__6cb952_idx'), models.Index(fields=['tenant_id', 'field_type'], name='custom_fiel_tenant__c8fc3d_idx')],
            },
        ),
    ]
