# Generated by Django 5.2.6 on 2026-03-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customfield'),
        ('api', '0009_make_task_optional_in_timelog'),
    ]

    operations = [
    ]
