# Generated by Django 5.2.6 on 2026-03-05 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260301_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this membership belongs to', null=True)),
                ('role', models.CharField(choices=[('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('developer', 'Developer'), ('member', 'Member')], default='member', help_text='Role in the sprint', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sprint_members',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this sprint belongs to', null=True)),
                ('name', models.CharField(help_text='Sprint name (e.g., Sprint 1)', max_length=200)),
                ('goal', models.TextField(blank=True, help_text='Sprint goal/objective', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed sprint description', null=True)),
                ('start_date', models.DateField(help_text='Sprint start date')),
                ('end_date', models.DateField(help_text='Sprint end date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current sprint status', max_length=20)),
                ('velocity_target', models.PositiveIntegerField(blank=True, help_text='Target story points for this sprint', null=True)),
                ('actual_velocity', models.PositiveIntegerField(blank=True, help_text='Actual story points completed', null=True)),
                ('retrospective_notes', models.TextField(blank=True, help_text='Sprint retrospective notes', null=True)),
                ('what_went_well', models.TextField(blank=True, help_text='What went well in this sprint', null=True)),
                ('what_to_improve', models.TextField(blank=True, help_text='What to improve next sprint', null=True)),
                ('action_items', models.TextField(blank=True, help_text='Action items from retrospective', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this sprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this sprint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.project')),
            ],
            options={
                'db_table': 'sprints',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='Sprint this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.sprint'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'sprint'], name='tasks_tenant__a1b04f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sprint', 'status'], name='tasks_sprint__893507_idx'),
        ),
        migrations.AddField(
            model_name='sprintmember',
            name='sprint',
            field=models.ForeignKey(help_text='Sprint this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.sprint'),
        ),
        migrations.AddField(
            model_name='sprintmember',
            name='user',
            field=models.ForeignKey(help_text='User who is a member of this sprint', on_delete=django.db.models.deletion.CASCADE, related_name='sprint_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant_id', 'project'], name='sprints_tenant__19ce9e_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant_id', 'status'], name='sprints_tenant__834617_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant_id', 'start_date', 'end_date'], name='sprints_tenant__a8a1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', 'status'], name='sprints_project_d1ab01_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintmember',
            index=models.Index(fields=['tenant_id', 'sprint'], name='sprint_memb_tenant__6cae73_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintmember',
            index=models.Index(fields=['tenant_id', 'user'], name='sprint_memb_tenant__15b380_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprintmember',
            constraint=models.UniqueConstraint(fields=('sprint', 'user'), name='uniq_sprint_user'),
        ),
    ]
