# Generated by Django 5.2.6 on 2026-03-18 05:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_sprint_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this priority belongs to', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Priority name (e.g., 'Critical')", max_length=50)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'critical')")),
                ('color', models.CharField(default='#ef4444', help_text='Hex color code (e.g., #ef4444)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code', regex='^#[0-9A-Fa-f]{6}$')])),
                ('icon', models.CharField(blank=True, help_text='Icon name (optional)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('weight', models.IntegerField(default=0, help_text='Weight for sorting/filtering (higher = more important)')),
                ('description', models.TextField(blank=True, help_text='Priority description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this priority is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_priorities',
                'ordering': ['order', 'weight', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'order'], name='task_priori_tenant__826cb0_idx'), models.Index(fields=['tenant_id', 'is_active'], name='task_priori_tenant__8c8a32_idx'), models.Index(fields=['tenant_id', 'slug'], name='task_priori_tenant__8aeee8_idx'), models.Index(fields=['tenant_id', 'weight'], name='task_priori_tenant__272c50_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'slug'), name='uniq_tenant_priority_slug')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='custom_priority',
            field=models.ForeignKey(blank=True, help_text='Custom priority (overrides priority field if set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.taskpriority'),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant this status belongs to', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Status name (e.g., 'In Review')", max_length=50)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'in-review')")),
                ('color', models.CharField(default='#8b5cf6', help_text='Hex color code (e.g., #8b5cf6)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code', regex='^#[0-9A-Fa-f]{6}$')])),
                ('icon', models.CharField(blank=True, help_text='Icon name (optional)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default status for new tasks')),
                ('is_final', models.BooleanField(default=False, help_text="Final status - tasks can't move from this status")),
                ('description', models.TextField(blank=True, help_text='Status description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_statuses',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'order'], name='task_status_tenant__622d78_idx'), models.Index(fields=['tenant_id', 'is_active'], name='task_status_tenant__5f6647_idx'), models.Index(fields=['tenant_id', 'slug'], name='task_status_tenant__af93e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'slug'), name='uniq_tenant_status_slug')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='custom_status',
            field=models.ForeignKey(blank=True, help_text='Custom status (overrides status field if set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.taskstatus'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'custom_status'], name='tasks_tenant__4dee4a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'custom_priority'], name='tasks_tenant__0ada2f_idx'),
        ),
    ]
