import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Eye, EyeOff, Loader2, User, Briefcase } from "lucide-react";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { AuthPageLayout } from "@/components/layout/AuthPageLayout";
import { useAuth } from "@/context/AuthContext";
import { apiService } from "@/lib/api";
import { toast } from "sonner";

const managerRegisterSchema = z
  .object({
    username: z.string().min(3, "Username must be at least 3 characters"),
    password: z.string().min(6, "Password must be at least 6 characters"),
    password_confirmation: z.string(),
    company_name: z.string().min(2, "Company name is required"),
    company_email: z.string().email("Please enter a valid email address"),
  })
  .refine((data) => data.password === data.password_confirmation, {
    message: "Passwords don't match",
    path: ["password_confirmation"],
  });

const agentRegisterSchema = z.object({
  username: z.string().min(3, "Username must be at least 3 characters"),
  password: z.string().min(6, "Password must be at least 6 characters"),
  password_confirmation: z.string(),
  company_id: z.string().min(3, "Company ID is required").max(20, "Company ID must be 20 characters or less"),
}).refine((data) => data.password === data.password_confirmation, {
  message: "Passwords don't match",
  path: ["password_confirmation"],
});

type ManagerRegisterFormData = z.infer<typeof managerRegisterSchema>;
type AgentRegisterFormData = z.infer<typeof agentRegisterSchema>;

export default function Register() {
  const navigate = useNavigate();
  const { login, register: registerUser, isLoading } = useAuth();
  const [userType, setUserType] = useState<"manager" | "agent">("manager");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const managerForm = useForm<ManagerRegisterFormData>({
    resolver: zodResolver(managerRegisterSchema),
  });

  const agentForm = useForm<AgentRegisterFormData>({
    resolver: zodResolver(agentRegisterSchema),
  });

  const handleManagerRegister = async (data: ManagerRegisterFormData) => {
    try {
      // Manager registration creates tenant + user
      const response = await apiService.register({
        email: data.username, // Use username as email
        password: data.password,
        password_confirmation: data.password_confirmation,
        first_name: "",
        last_name: "",
        phone: "",
        company: data.company_name,
        company_id: "", // Will be auto-generated by backend
        type: "manager",
        // Manager-specific fields
        company_name: data.company_name,
        company_email: data.company_email,
        role: "manager",
      } as any);

      if (response.success) {
        const companyId = response.data?.company_id || "";
        if (companyId) {
          toast.success(`Manager account created! Your Company ID is: ${companyId}`);
        } else {
          toast.success("Manager account created successfully!");
        }
        
        // Auto-login after registration
        // For managers, company_id is optional (backend finds from user.tenant_id)
        const loginResponse = await login({
          email: data.username,
          password: data.password,
          company_id: "", // Empty for managers, backend will find tenant from user.tenant_id
        });

        if (loginResponse.success) {
          navigate("/dashboard");
        } else {
          navigate("/login");
        }
      } else {
        // Show detailed errors
        const errorMessage = response.message || "Registration failed";
        const errors = response.errors || {};
        
        // Display field-specific errors
        Object.keys(errors).forEach((field) => {
          const fieldErrors = Array.isArray(errors[field]) ? errors[field] : [errors[field]];
          fieldErrors.forEach((error: string) => {
            toast.error(`${field}: ${error}`);
          });
        });
        
        // Also show general message
        if (Object.keys(errors).length === 0) {
          toast.error(errorMessage);
        }
      }
    } catch (error: any) {
      toast.error(error.message || "An error occurred during registration");
    }
  };

  const handleAgentRegister = async (data: AgentRegisterFormData) => {
    try {
      // Agent registration uses existing tenant
      const success = await registerUser({
        email: data.username, // Use username as email
        password: data.password,
        password_confirmation: data.password_confirmation,
        first_name: "",
        last_name: "",
        phone: "",
        company: "",
        company_id: data.company_id.toUpperCase(),
        type: "agent",
        role: "agent",
      } as any);

      if (success) {
        toast.success("Agent account created successfully!");
        // AuthContext register function already handles tokens and user state
        navigate("/dashboard");
      } else {
        // Show detailed errors
        const errorMessage = response.message || "Registration failed";
        const errors = response.errors || {};
        
        // Display field-specific errors
        Object.keys(errors).forEach((field) => {
          const fieldErrors = Array.isArray(errors[field]) ? errors[field] : [errors[field]];
          fieldErrors.forEach((error: string) => {
            toast.error(`${field}: ${error}`);
          });
        });
        
        // Also show general message
        if (Object.keys(errors).length === 0) {
          toast.error(errorMessage);
        }
      }
    } catch (error: any) {
      toast.error(error.message || "An error occurred during registration");
    }
  };

  return (
    <AuthPageLayout showAuthLinks={false}>
      <div className="w-full max-w-md">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <Card className="bg-white/5 border-white/10 backdrop-blur-md">
            <CardHeader className="text-center">
              <Link to="/" className="flex items-center justify-center space-x-2 mb-4">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets%2F9904588c60fb490e85274cacb675da8b%2F3b2338ca45e44b4c92f4630003d43891?format=webp&width=800"
                  alt="NITTIVA"
                  className="h-10 w-auto hover:opacity-80 transition-opacity"
                />
              </Link>
              <CardTitle className="text-2xl text-white">Join NITTIVA</CardTitle>
              <CardDescription className="text-gray-300">
                Register as Manager or Agent
              </CardDescription>
            </CardHeader>

            <CardContent className="space-y-4">
              {/* User Type Selection */}
              <div className="flex gap-2 p-1 bg-white/5 rounded-lg">
                <Button
                  type="button"
                  variant={userType === "manager" ? "default" : "ghost"}
                  onClick={() => setUserType("manager")}
                  className={`flex-1 ${
                    userType === "manager"
                      ? "bg-accent text-black hover:bg-accent/80"
                      : "text-gray-400 hover:text-white"
                  }`}
                >
                  <Briefcase className="w-4 h-4 mr-2" />
                  Manager
                </Button>
                <Button
                  type="button"
                  variant={userType === "agent" ? "default" : "ghost"}
                  onClick={() => setUserType("agent")}
                  className={`flex-1 ${
                    userType === "agent"
                      ? "bg-accent text-black hover:bg-accent/80"
                      : "text-gray-400 hover:text-white"
                  }`}
                >
                  <User className="w-4 h-4 mr-2" />
                  Agent
                </Button>
              </div>

              {/* Manager Registration Form */}
              {userType === "manager" && (
                <form
                  onSubmit={managerForm.handleSubmit(handleManagerRegister)}
                  className="space-y-4"
                >
                  <div className="space-y-2">
                    <Label htmlFor="manager_username" className="text-white">
                      Manager Username *
                    </Label>
                    <Input
                      id="manager_username"
                      placeholder="Enter your username"
                      className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400"
                      {...managerForm.register("username")}
                    />
                    {managerForm.formState.errors.username && (
                      <p className="text-red-400 text-sm">
                        {managerForm.formState.errors.username.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="manager_password" className="text-white">
                      Password *
                    </Label>
                    <div className="relative">
                      <Input
                        id="manager_password"
                        type={showPassword ? "text" : "password"}
                        placeholder="Enter your password"
                        className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400 pr-10"
                        {...managerForm.register("password")}
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white"
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {managerForm.formState.errors.password && (
                      <p className="text-red-400 text-sm">
                        {managerForm.formState.errors.password.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="manager_confirm_password" className="text-white">
                      Confirm Password *
                    </Label>
                    <div className="relative">
                      <Input
                        id="manager_confirm_password"
                        type={showConfirmPassword ? "text" : "password"}
                        placeholder="Confirm your password"
                        className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400 pr-10"
                        {...managerForm.register("password_confirmation")}
                      />
                      <button
                        type="button"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white"
                      >
                        {showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {managerForm.formState.errors.password_confirmation && (
                      <p className="text-red-400 text-sm">
                        {managerForm.formState.errors.password_confirmation.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="company_name" className="text-white">
                      Company Name *
                    </Label>
                    <Input
                      id="company_name"
                      placeholder="Enter your company name"
                      className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400"
                      {...managerForm.register("company_name")}
                    />
                    {managerForm.formState.errors.company_name && (
                      <p className="text-red-400 text-sm">
                        {managerForm.formState.errors.company_name.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="company_email" className="text-white">
                      Company Email *
                    </Label>
                    <Input
                      id="company_email"
                      type="email"
                      placeholder="company@example.com"
                      className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400"
                      {...managerForm.register("company_email")}
                    />
                    {managerForm.formState.errors.company_email && (
                      <p className="text-red-400 text-sm">
                        {managerForm.formState.errors.company_email.message}
                      </p>
                    )}
                  </div>

                  <Button
                    type="submit"
                    className="w-full bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white"
                    disabled={isLoading}
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Creating Account...
                      </>
                    ) : (
                      "Register as Manager"
                    )}
                  </Button>
                </form>
              )}

              {/* Agent Registration Form */}
              {userType === "agent" && (
                <form
                  onSubmit={agentForm.handleSubmit(handleAgentRegister)}
                  className="space-y-4"
                >
                  <div className="space-y-2">
                    <Label htmlFor="agent_username" className="text-white">
                      Agent Username *
                    </Label>
                    <Input
                      id="agent_username"
                      placeholder="Enter your username"
                      className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400"
                      {...agentForm.register("username")}
                    />
                    {agentForm.formState.errors.username && (
                      <p className="text-red-400 text-sm">
                        {agentForm.formState.errors.username.message}
                      </p>
                    )}
                    <p className="text-xs text-gray-400">
                      This will be your login username
                    </p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="agent_password" className="text-white">
                      Password *
                    </Label>
                    <div className="relative">
                      <Input
                        id="agent_password"
                        type={showPassword ? "text" : "password"}
                        placeholder="Enter your password"
                        className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400 pr-10"
                        {...agentForm.register("password")}
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white"
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {agentForm.formState.errors.password && (
                      <p className="text-red-400 text-sm">
                        {agentForm.formState.errors.password.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="agent_confirm_password" className="text-white">
                      Confirm Password *
                    </Label>
                    <div className="relative">
                      <Input
                        id="agent_confirm_password"
                        type={showConfirmPassword ? "text" : "password"}
                        placeholder="Confirm your password"
                        className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400 pr-10"
                        {...agentForm.register("password_confirmation")}
                      />
                      <button
                        type="button"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white"
                      >
                        {showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {agentForm.formState.errors.password_confirmation && (
                      <p className="text-red-400 text-sm">
                        {agentForm.formState.errors.password_confirmation.message}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="company_id" className="text-white">
                      Company ID * <span className="text-red-400">*</span>
                    </Label>
                    <Input
                      id="company_id"
                      type="text"
                      placeholder="Enter Company ID (e.g., YYT6USJJ)"
                      className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-blue-400 uppercase"
                      style={{ textTransform: "uppercase" }}
                      {...agentForm.register("company_id")}
                      onChange={(e) => {
                        e.target.value = e.target.value.toUpperCase();
                        agentForm.register("company_id").onChange(e);
                      }}
                    />
                    <p className="text-xs text-gray-400">
                      Get this from your manager
                    </p>
                    {agentForm.formState.errors.company_id && (
                      <p className="text-red-400 text-sm">
                        {agentForm.formState.errors.company_id.message}
                      </p>
                    )}
                  </div>

                  <Button
                    type="submit"
                    className="w-full bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white"
                    disabled={isLoading}
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Creating Account...
                      </>
                    ) : (
                      "Register as Agent"
                    )}
                  </Button>
                </form>
              )}

              <div className="text-center pt-4 border-t border-white/10">
                <p className="text-gray-300">
                  Already have an account?{" "}
                  <Link
                    to="/login"
                    className="text-blue-400 hover:text-blue-300 font-medium"
                  >
                    Sign in
                  </Link>
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </AuthPageLayout>
  );
}
