"""
User serializers.

This module contains serializers for user registration and user data.
"""

from rest_framework import serializers
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password

User = get_user_model()


class RegisterSerializer(serializers.ModelSerializer):
    """Serializer for user registration (Manager and Agent)."""

    first_name = serializers.CharField(write_only=True, required=False, allow_blank=True)
    last_name = serializers.CharField(write_only=True, required=False, allow_blank=True)
    password = serializers.CharField(write_only=True, validators=[validate_password])
    password_confirmation = serializers.CharField(write_only=True, required=False, allow_blank=True)
    phone_number = serializers.CharField(write_only=True, required=False, allow_blank=True)
    company = serializers.CharField(write_only=True, required=False, allow_blank=True)
    company_id = serializers.CharField(write_only=True, required=False, allow_blank=True, help_text="Company ID (required for agents, optional for managers)")
    company_name = serializers.CharField(write_only=True, required=False, allow_blank=True, help_text="Company name (required for managers)")
    company_email = serializers.EmailField(write_only=True, required=False, allow_blank=True, help_text="Company email (required for managers)")
    # Email field - accept username format (not strict email validation)
    email = serializers.CharField(required=True, help_text="Username (used as email)")

    class Meta:
        model = User
        fields = [
            "id",
            "email",
            "name",
            "role",
            "password",
            "password_confirmation",
            "first_name",
            "last_name",
            "phone_number",
            "company",
            "company_id",
            "company_name",
            "company_email",
        ]
        extra_kwargs = {"role": {"required": False}, "name": {"required": False}}
    
    def validate_email(self, value):
        """Validate email/username - accept any string, format as email-like for storage."""
        if not value or not value.strip():
            raise serializers.ValidationError("Username is required.")
        # Convert username to email-like format if it doesn't contain @
        value = value.strip()
        if '@' not in value:
            # If no @, append @example.com to make it a valid email format for Django
            value = f"{value}@example.com"
        return value.lower()

    def validate(self, attrs):
        """Validate registration data based on role."""
        if attrs.get("password") != attrs.get("password_confirmation"):
            raise serializers.ValidationError({"password_confirmation": "Passwords do not match"})
        
        role = attrs.get("role", "").lower()
        company_id = attrs.get("company_id", "").strip()
        company_name = attrs.get("company_name", "").strip()
        company_email = attrs.get("company_email", "").strip()
        
        # Manager registration: requires company_name and company_email, creates tenant
        if role == "manager":
            if not company_name:
                raise serializers.ValidationError({
                    "company_name": "Company name is required for manager registration."
                })
            if not company_email:
                raise serializers.ValidationError({
                    "company_email": "Company email is required for manager registration."
                })
            # Company ID will be auto-generated by backend
        
        # Agent registration: requires company_id, uses existing tenant
        elif role == "agent":
            if not company_id:
                raise serializers.ValidationError({
                    "company_id": "Company ID is required for agent registration. Get this from your manager."
                })
            # Look up tenant by company_id
            from ..models import Tenant
            try:
                tenant = Tenant.objects.get(company_id=company_id.upper().strip(), is_active=True)
                self.context['tenant'] = tenant
            except Tenant.DoesNotExist:
                raise serializers.ValidationError({
                    "company_id": f"Invalid company ID '{company_id}'. Please check with your manager."
                })
        else:
            # Default/legacy: requires company_id
            if not company_id:
                raise serializers.ValidationError({
                    "company_id": "Company ID is required."
                })
            from ..models import Tenant
            try:
                tenant = Tenant.objects.get(company_id=company_id.upper().strip(), is_active=True)
                self.context['tenant'] = tenant
            except Tenant.DoesNotExist:
                raise serializers.ValidationError({
                    "company_id": f"Invalid company ID '{company_id}'. Please check with your administrator."
                })
        
        return attrs

    def create(self, validated_data):
        """Create a new user and optionally create tenant for managers."""
        # Remove fields that don't exist on User model
        validated_data.pop("password_confirmation", None)
        validated_data.pop("phone_number", None)
        validated_data.pop("company", None)
        company_id = validated_data.pop("company_id", "").strip()
        company_name = validated_data.pop("company_name", "").strip()
        company_email = validated_data.pop("company_email", "").strip()
        role = validated_data.get("role", "").lower()
        
        first = validated_data.pop("first_name", "").strip()
        last = validated_data.pop("last_name", "").strip()
        if not validated_data.get("name"):
            validated_data["name"] = f"{first} {last}".strip() or validated_data.get("email", "").split("@")[0]

        tenant = None
        
        # Manager registration: create tenant first
        if role == "manager":
            from ..models import Tenant
            import secrets
            
            # Generate company_id if not provided
            if not company_id:
                max_attempts = 10
                for _ in range(max_attempts):
                    company_id = secrets.token_urlsafe(6).upper().replace('-', '').replace('_', '')[:8]
                    if not Tenant.objects.filter(company_id=company_id).exists():
                        break
                else:
                    import uuid
                    company_id = str(uuid.uuid4())[:8].upper()
            
            # Create tenant
            tenant = Tenant.objects.create(
                company_id=company_id.upper(),
                name=company_name,
                email=company_email,
                is_active=True,
                is_trial=True,  # New tenants start as trial
            )
            validated_data["tenant_id"] = tenant.id
            validated_data["role"] = "manager"
            
            # Store company_id in context for response
            self.context['created_company_id'] = company_id
        
        # Agent registration: use existing tenant from context
        elif role == "agent":
            tenant = self.context.get('tenant')
            if not tenant:
                raise serializers.ValidationError({
                    "company_id": "Tenant not found. Please check your company ID."
                })
            validated_data["tenant_id"] = tenant.id
            validated_data["role"] = "agent"
        
        # Legacy/default: use tenant from context
        else:
            tenant = self.context.get('tenant')
            if not tenant:
                if company_id:
                    from ..models import Tenant
                    try:
                        tenant = Tenant.objects.get(company_id=company_id.upper().strip(), is_active=True)
                    except Tenant.DoesNotExist:
                        pass
            
            if not tenant:
                raise serializers.ValidationError({
                    "company_id": "Tenant not found. Please check your company ID."
                })
            validated_data["tenant_id"] = tenant.id

        password = validated_data.pop("password")
        
        try:
            user = User.objects.create(**validated_data)
            user.set_password(password)
            user.save()
            
            # Company ID is stored in context, will be returned in view response
            
            return user
        except Exception as e:
            # Handle unique constraint violations
            if "unique" in str(e).lower() or "duplicate" in str(e).lower():
                raise serializers.ValidationError({
                    "email": "A user with this email already exists in this tenant."
                })
            raise serializers.ValidationError({
                "non_field_errors": [f"Failed to create user: {str(e)}"]
            })


class UserSerializer(serializers.ModelSerializer):
    """Serializer for user data."""
    
    company_id = serializers.SerializerMethodField(help_text="Company ID from user's tenant")

    class Meta:
        model = User
        fields = [
            "id",
            "email",
            "name",
            "role",
            "is_active",
            "is_staff",
            "is_superuser",
            "created_at",
            "updated_at",
            "profile_image_url",
            "auth_provider",
            "company_id",
        ]
    
    def get_company_id(self, obj):
        """Get company_id from user's tenant."""
        if obj.tenant_id:
            try:
                from ..models import Tenant
                tenant = Tenant.objects.get(id=obj.tenant_id)
                return tenant.company_id
            except Tenant.DoesNotExist:
                return None
        return None


class GoogleAuthSerializer(serializers.Serializer):
    """Serializer for Google OAuth authentication."""

    token = serializers.CharField(required=True, write_only=True)

